### ISSUE TITLE
Not showing the error stopping the simulation

### ISSUE THREAD

**Issue by rwadhwa910** [NREL/OpenStudio-PAT#186]
When I am  trying to run a simulation, the system does not show as to what is stopping the simulation, although going to the console shows the error. Attached is the image which shows there is an error related to WWR measure but does not show that error in the app.

Windows 10
PAT 3.2.0

![PAT_Error](https://user-images.githubusercontent.com/63880759/122966476-fec27a00-d34e-11eb-8cba-8bc1b71927c7.PNG)

**Comment by DavidGoldwasser** [comment]
@rwadhwa910 it seems like maybe there are two parts to this question.

1. An enhancement to PAT to have the errors or at least the relevant ones show up in the dialog without going to developer tools. That makes sense. If we can't get that to work maybe just update message to say to look in developer console with some guidance to open it)
2. The second part may be more specifically what is the wwr error you are seeing about. Within the Error I see  'Set Window to Wall Ratio by Facade" argument 'wwr' does not have a value for option '0.3'. That 0.3 is just the string given to the name of one of your measure options. If you go to the first tab make sure that the wwr field in the measure has a value. There is a default value of 0.3, but if that got removed in PAT it might show up like any empty string which would be an invalid double value. If the measure was able to run it would use the default, but the analysis is stopping because it looks invalid. If that doesn't fix it, then you can email me your PAT project zipped up we can take a look at it and try to replicate it.

**Comment by rwadhwa910** [comment]
@DavidGoldwasser  I agree with you one can go into the developer's tool and look for the error, but I believe for a new beginner I think it will be difficult to see what is the error, that's why it would be great if the error shows on the screen. Also I was able to run this model by doing the changes. Thanks!
