### ISSUE TITLE
Empty string or string with just space as string argument value is not treated as valid in PAT but is in OS app 

### ISSUE THREAD

**Issue by kflemin** [NREL/OpenStudio-PAT#44]
_From @DavidGoldwasser on November 9, 2017 17:59_

I hit this in reporting measures for internal project where some times I want an argument value to be an empty string. The measure ran fine with this in OS app, but failed to make an OSA in PAT. I even tried changing the string argument value to a space vs. an empty string. Should have same behavior from OS app or PAT.

![screen shot 2017-11-09 at 11 05 11 am](https://user-images.githubusercontent.com/4857055/32621644-b05e556e-c53d-11e7-8e9b-371b2c3a63ec.png)

_Copied from original issue: NREL/OpenStudio#2842_

**Comment by kflemin** [comment]
@DavidGoldwasser, can you provide a PAT project to test with, or at least a measure where a blank argument would be valid?  thanks!

**Comment by kflemin** [comment]
A blank space gets recorded as an empty string in the grid. An argument that can have a valid value be an empty string should probably be made an optional argument.  That way, the validation shown in the screenshot above would not get triggered.  I'm not sure what kind of validation is done on arguments in the App. @macumber?

**Comment by macumber** [comment]
I would second that empty string "" or blank space " " are not good input,, these should be considered equivalent

**Comment by DavidGoldwasser** [comment]
Just to clarify about grid in PAT, it will remove any leading or trailing spaces, still an edge case, but there are use cases for that, for example there is a measure that does find and replace on object names in the model. I might want to replace "Prototype " in object names with "prototype_".

@macumber for some background, here is what happens in OS app. I have a measure with this argument

    sql_key = OpenStudio::Ruleset::OSArgument.makeStringArgument("key_value", true)
    sql_key.setDisplayName("SQL key value")
    sql_key.setDescription("SQL key value for the SQL query to find the variable in the SQL file")
    sql_key.setDefaultValue("")
    args << sql_key 

When if the string is empty that argument is just removed from the OSW and the measure runs fine. It does accept " " as an argument as well as leading and trailing spaces.

Here is that the OSW looks like when the required string is empty.

>          "arguments" : {
            "add_first_zero_for_plots" : true,
            "add_last_zero_for_plots" : true,
            "convert_data" : "WH to J",
            "csv_name" : "/Users/dgoldwas/Documents/GitHub/NREL/FRP_Models/2015_measured_data/FRP2_HVAC_15m_NREL_adj_rtu_fan_st_12am.csv",
            "csv_time_header" : "TIMESTAMP",
            "csv_var" : "Heating_Tot_electric",
            "csv_var_dn" : "Heating_Tot_electric",
            "environment_period" : "January,February_a,February_b,March,July,August,September,October,November_a,November_b,December",
            "find_avail" : false,
            "plot_name" : "Heating Facility",
            "seconds" : false,
            "timeseries_name" : "Heating:Electricity",
            "warning_messages" : false
         },

vs. this

>          "arguments" : {
            "add_first_zero_for_plots" : true,
            "add_last_zero_for_plots" : true,
            "convert_data" : "WH to J",
            "csv_name" : "/Users/dgoldwas/Documents/GitHub/NREL/FRP_Models/2015_measured_data/FRP2_HVAC_15m_NREL_adj_rtu_fan_st_12am.csv",
            "csv_time_header" : "TIMESTAMP",
            "csv_var" : "Heating_Tot_electric",
            "csv_var_dn" : "Heating_Tot_electric",
            "environment_period" : "January,February_a,February_b,March,July,August,September,October,November_a,November_b,December",
            "find_avail" : false,
            "key_value" : "asdf",
            "plot_name" : "Heating Facility",
            "seconds" : false,
            "timeseries_name" : "Heating:Electricity",
            "warning_messages" : false
         },

**Comment by DavidGoldwasser** [comment]
I am fine with app being changed to not allow empty strings. In the past you would see a red triangle showing that data was missing(Update: that shows up if no default, but if default is empty string it doesn't stop you from using that). I can update the measure to use an optional argument or a special string for no key.

I didn't write the measure was just using it for calibration project, and just got confused when I built the exact same workflow in PAT as OS app that it didnt' run.

A related question is should the CLI run with empty string for required arg or should it stop. Many measures will check for this and registerError and false, but for this particular measure it doesn't check since sometimes the required key is an empty string.

**Comment by kflemin** [comment]
The whitespace trimming is a separate issue (and I've just fixed it 3a68b8465ffd3133232f36950f5a08a93fa08923).  Can we close this issue?  You can open another one in the OpenStudio repo if you need to.

**Comment by macumber** [comment]
I think it would be worth making a little table of expected behavior, we could make a test measure to verify.  I'm not sure if the table below is correct, but I think we need this level of specification, should get posted in the measure writing guide.  We should also mention that default value can't be "" or " ", and this only applies to string and choice arguments.  

Required | Default | User Input | GUI Error | Key in OSW | Key Value in OSW | Note
--------- | --------|------------|-----------|--------------|-------------------|-----
true | true | "" | false | true? | default value? | Do we allow defaults for required fields?
true | false | "" | Missing Required Input | false | NA | 
true | true | " " | false | true? | default value? | Do we allow defaults for required fields?
true | false | " " | Missing Required Input | false | NA | 
false | true | "" | false | true? | default value? | We don't write the default value to the OSW do we?
false | false | "" | false | false | NA
false | true | " " | false | true? | default value? | We don't write the default value to the OSW do we?
false | false | " " | false | false | NA
